### ISSUE TITLE
Plugin makes editing large documents incredibly slow

### ISSUE THREAD

**Issue by mcepl** [danielbmarques/vim-ditto#6]
When doing even simple operations (``gqap``) on very large documents (whole text of Harry Potter and Deathly Hallows in Czech, 27445 lines) it takes very long time (tens of seconds) before the operation finishes.

See here [profile-log.txt](https://github.com/dbmrq/vim-ditto/files/1143251/profile-log.txt) generated by ``:profile`` operations (according to this [HOWTO](https://www.systutorials.com/136414/profiling-vim-to-find-out-which-plugin-makes-vim-slow/)) and notice how reformatting one paragraph (twenty or so lines of text) leads to twenty or more seconds delay.

Would it be possible to somehow use ``async`` facilities in vim 8.0 and do all necessary analysis in the background, so that vim doesn’t freeze? Or would it be possible to use [asyncrun.vim](https://github.com/skywind3000/asyncrun.vim.git) or something similar?

**Comment by dbmrq** [comment]
I don't think the async features apply, since I'm not running any external commands, everything is done by Vim itself.

Ditto's `autocmd`s aren't really meant to be used with such huge documents. In that case I think the best option is to disable them (`:DittoOff`) and run Ditto on specific paragraphs/sections. You can, for instance, select some text and run `:Ditto` on the selection, and you could create a mapping to do that for you or even map something like `gq` to run `:Ditto` after formatting the text.

The problem with the `autocmd`s is that even if you change a single paragraph the highlighting has to be updated on every line after that paragraph. If you add a line to the first paragraph, for instance, the highlighting of every other paragraph will be off by one line. It's like the highlighting stays in place when every line actually went down. I don't see how to work around that, so I'll close this for now, but any suggestions are more than welcome.

**Comment by mcepl** [comment]
You are right, it would be probably better then if the checking was done by the external process, we can use it as a process managed by ``syntastic`` or ``ale`` or something like that. Do you know about the external process equivalent of ditto as a standalone script?

**Comment by dbmrq** [comment]
Yeah, that would be interesting, but I don't know of anything like it. I guess we'd have to rewrite that part of Leio as an external script, but I'm not sure it's worth the trouble. Even if it works, Vim won't hang on huge files, but it'll still take a while for the highlighting to be updated, which would be pretty much like my suggestion of replacing the `autocmd`s. I think it's better to keep it simple and just use different `autocmd`s on big files, maybe just highlight the current paragraph instead of the whole text.
